{% set name = "lit-nlp" %}
{% set github_name = "lit" %}
{% set version = "13.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ github_name[0] }}/{{ github_name }}/{{ github_name }}-{{ version }}.tar.gz
  sha256: c6ca0b36e2581f51db690a9b907b64847bb289448fe7222d0dafd7f83dde34e8

build:
  number: 0
  noarch: python
  entry_points:
    - lit = lit.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - lit
    - lit.builtin_commands
    - lit.formats
    - lit.llvm
  commands:
    - pip check
    - lit --help
  requires:
    - pip

about:
  home: https://github.com/PAIR-code/lit
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.TXT
  summary: The Language Interpretability Tool (LIT) is a visual, interactive model-understanding tool for NLP models.
  doc_url: https://pypi.org/project/lit-nlp/
  dev_url: https://github.com/PAIR-code/lit

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - RyanHackney
    - oblute
