{% set name = "lit-nlp" %}
{% set github_name = "lit" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ github_name[0] }}/{{ github_name }}/{{ github_name }}-{{ version }}.tar.gz
  sha256: 2b15be8a84b691d9473911e7a73100e8ba3abef4965920ef6ac65a7d75dc3936

build:
  number: 1
  entry_points:
    - lit = lit.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - lit
    - lit.builtin_commands
    - lit.formats
    - lit.llvm
  commands:
    - lit --help

about:
  home: https://github.com/PAIR-code/lit
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.TXT
  summary: The Language Interpretability Tool (LIT) is a visual, interactive model-understanding tool for NLP models.
  doc_url: https://pypi.org/project/lit-nlp/
  dev_url: https://github.com/PAIR-code/lit

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - RyanHackney
    - oblute
