{% set name = "lit-nlp" %}
{% set github_name = "lit" %}
{% set version = "12.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ github_name[0] }}/{{ github_name }}/{{ github_name }}-{{ version }}.tar.gz
  sha256: e187d3210033f8af931c3e1d54144afcca7e1f3de329663e638e7cd7644fb4ac

build:
  number: 0
  entry_points:
    - lit = lit.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - lit
    - lit.builtin_commands
    - lit.formats
    - lit.llvm
  commands:
    - lit --help

about:
  home: https://github.com/PAIR-code/lit
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.TXT
  summary: The Language Interpretability Tool (LIT) is a visual, interactive model-understanding tool for NLP models.
  doc_url: https://pypi.org/project/lit-nlp/
  dev_url: https://github.com/PAIR-code/lit

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - RyanHackney
    - oblute
